"""Category keyword definitions for fast classification."""

DEFAULT_CATEGORIES = [
    {"slug": "tech", "name": "Technology"},
    {"slug": "ai", "name": "Artificial Intelligence"},
    {"slug": "crypto", "name": "Crypto & Web3"},
    {"slug": "business", "name": "Business"},
    {"slug": "science", "name": "Science"},
    {"slug": "health", "name": "Health & Wellness"},
    {"slug": "culture", "name": "Culture & Entertainment"},
    {"slug": "politics", "name": "Politics"},
    {"slug": "gaming", "name": "Gaming"},
    {"slug": "finance", "name": "Finance & Markets"},
    {"slug": "sports", "name": "Sports"},
    {"slug": "design", "name": "Design & UX"},
    {"slug": "devtools", "name": "Developer Tools"},
    {"slug": "opensource", "name": "Open Source"},
]

# (keyword, weight) pairs for each category
CATEGORY_KEYWORDS: dict[str, list[tuple[str, float]]] = {
    "ai": [
        ("artificial intelligence", 3.0), ("machine learning", 3.0), ("deep learning", 3.0),
        ("neural network", 2.5), ("gpt", 2.5), ("llm", 2.5), ("large language model", 3.0),
        ("chatgpt", 2.5), ("claude", 2.0), ("openai", 2.5), ("anthropic", 2.0),
        ("transformer", 2.0), ("diffusion", 1.5), ("generative ai", 3.0),
        ("nlp", 2.0), ("computer vision", 2.0), ("reinforcement learning", 2.0),
        ("training", 1.0), ("inference", 1.5), ("fine-tuning", 2.0), ("finetuning", 2.0),
        ("embedding", 1.5), ("rag", 1.5), ("agent", 1.0), ("ai agent", 2.5),
        ("stable diffusion", 2.0), ("midjourney", 2.0), ("dall-e", 2.0),
        ("copilot", 1.5), ("hugging face", 2.0), ("pytorch", 2.0), ("tensorflow", 2.0),
    ],
    "tech": [
        ("software", 1.5), ("hardware", 1.5), ("startup", 1.5), ("silicon valley", 1.5),
        ("apple", 1.5), ("google", 1.5), ("microsoft", 1.5), ("amazon", 1.0),
        ("meta", 1.0), ("iphone", 1.5), ("android", 1.5), ("cloud", 1.0),
        ("saas", 1.5), ("api", 1.0), ("platform", 0.5), ("tech", 1.0),
        ("semiconductor", 2.0), ("chip", 1.0), ("nvidia", 2.0), ("intel", 1.5),
        ("amd", 1.5), ("quantum", 2.0), ("robotics", 2.0), ("drone", 1.5),
        ("ev", 1.0), ("electric vehicle", 1.5), ("tesla", 1.5), ("spacex", 1.5),
    ],
    "crypto": [
        ("bitcoin", 3.0), ("ethereum", 3.0), ("crypto", 2.5), ("cryptocurrency", 3.0),
        ("blockchain", 2.5), ("defi", 2.5), ("nft", 2.0), ("web3", 2.5),
        ("token", 1.5), ("wallet", 1.0), ("mining", 1.0), ("staking", 2.0),
        ("solana", 2.0), ("cardano", 2.0), ("polygon", 1.5), ("binance", 2.0),
        ("coinbase", 2.0), ("dex", 2.0), ("smart contract", 2.5), ("dao", 2.0),
        ("metaverse", 1.5), ("altcoin", 2.0),
    ],
    "business": [
        ("startup", 1.5), ("funding", 2.0), ("ipo", 2.5), ("acquisition", 2.0),
        ("merger", 2.0), ("revenue", 1.5), ("profit", 1.5), ("ceo", 1.5),
        ("layoff", 2.0), ("hiring", 1.5), ("valuation", 2.0), ("series a", 2.5),
        ("venture capital", 2.5), ("vc", 1.5), ("unicorn", 2.0), ("earnings", 2.0),
        ("market cap", 1.5), ("growth", 0.5), ("enterprise", 1.0),
    ],
    "science": [
        ("research", 1.0), ("study", 0.5), ("discovery", 1.5), ("experiment", 1.5),
        ("nasa", 2.0), ("space", 1.5), ("physics", 2.0), ("biology", 2.0),
        ("chemistry", 2.0), ("climate", 2.0), ("genome", 2.0), ("crispr", 2.5),
        ("vaccine", 2.0), ("neuroscience", 2.0), ("astronomy", 2.0),
        ("mars", 1.5), ("telescope", 1.5), ("particle", 1.5),
    ],
    "health": [
        ("health", 1.5), ("medical", 1.5), ("disease", 1.5), ("treatment", 1.5),
        ("drug", 1.5), ("fda", 2.0), ("clinical trial", 2.5), ("cancer", 2.0),
        ("mental health", 2.5), ("wellness", 1.5), ("fitness", 1.5),
        ("nutrition", 1.5), ("pandemic", 2.0), ("virus", 1.5), ("hospital", 1.0),
    ],
    "culture": [
        ("movie", 1.5), ("film", 1.5), ("music", 1.5), ("album", 1.5),
        ("tv show", 2.0), ("series", 0.5), ("netflix", 1.5), ("disney", 1.5),
        ("concert", 1.5), ("celebrity", 1.5), ("meme", 2.0), ("viral", 1.5),
        ("tiktok", 1.5), ("youtube", 1.0), ("streaming", 1.0), ("artist", 1.0),
        ("entertainment", 1.5), ("award", 1.0), ("oscar", 2.0), ("grammy", 2.0),
    ],
    "politics": [
        ("president", 2.0), ("election", 2.5), ("congress", 2.0), ("senate", 2.0),
        ("government", 1.5), ("policy", 1.5), ("law", 1.0), ("regulation", 1.5),
        ("vote", 1.5), ("democrat", 2.0), ("republican", 2.0), ("supreme court", 2.5),
        ("legislation", 2.0), ("sanction", 2.0), ("geopolitics", 2.0),
    ],
    "gaming": [
        ("game", 1.5), ("gaming", 2.0), ("steam", 1.5), ("playstation", 2.0),
        ("xbox", 2.0), ("nintendo", 2.0), ("esports", 2.5), ("fps", 1.5),
        ("rpg", 1.5), ("mmorpg", 2.0), ("indie game", 2.0), ("game dev", 2.0),
        ("unreal engine", 2.0), ("unity", 1.5), ("valve", 1.5),
        ("twitch", 1.5), ("speedrun", 2.0),
    ],
    "finance": [
        ("stock", 2.0), ("market", 1.0), ("trading", 1.5), ("investment", 1.5),
        ("wall street", 2.0), ("fed", 2.0), ("interest rate", 2.5),
        ("inflation", 2.0), ("recession", 2.5), ("s&p", 2.0), ("nasdaq", 2.0),
        ("forex", 2.0), ("bond", 1.5), ("etf", 2.0), ("hedge fund", 2.0),
        ("banking", 1.5), ("fintech", 2.0),
    ],
    "sports": [
        ("nba", 2.5), ("nfl", 2.5), ("soccer", 2.0), ("football", 1.5),
        ("basketball", 2.0), ("baseball", 2.0), ("tennis", 2.0), ("f1", 2.0),
        ("formula 1", 2.5), ("olympics", 2.5), ("world cup", 2.5),
        ("championship", 1.5), ("tournament", 1.5), ("athlete", 1.5),
        ("ufc", 2.0), ("mma", 2.0),
    ],
    "design": [
        ("design", 1.5), ("ux", 2.0), ("ui", 2.0), ("figma", 2.5),
        ("typography", 2.0), ("branding", 1.5), ("illustration", 1.5),
        ("user experience", 2.5), ("accessibility", 1.5), ("color palette", 2.0),
        ("prototype", 1.5), ("wireframe", 2.0), ("design system", 2.5),
    ],
    "devtools": [
        ("developer tool", 3.0), ("ide", 2.0), ("vscode", 2.5), ("vim", 2.0),
        ("git", 1.5), ("github", 1.5), ("gitlab", 1.5), ("docker", 2.0),
        ("kubernetes", 2.0), ("ci/cd", 2.5), ("devops", 2.0), ("terraform", 2.0),
        ("cli", 1.5), ("terminal", 1.5), ("debugging", 1.5), ("linter", 2.0),
        ("compiler", 2.0), ("sdk", 1.5), ("framework", 1.0), ("library", 0.5),
        ("rust", 1.5), ("go", 1.0), ("typescript", 1.5), ("python", 1.0),
        ("react", 1.5), ("next.js", 2.0), ("node", 1.0), ("bun", 2.0),
        ("deno", 2.0), ("wasm", 2.0), ("webassembly", 2.5),
    ],
    "opensource": [
        ("open source", 3.0), ("open-source", 3.0), ("oss", 2.0),
        ("github", 1.0), ("fork", 1.5), ("pull request", 2.0), ("contributor", 1.5),
        ("license", 1.5), ("mit license", 2.0), ("apache", 1.0), ("gpl", 2.0),
        ("linux", 2.0), ("free software", 2.5),
    ],
}
